# Generated by Django 4.2.20 on 2025-05-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocall',
            options={'verbose_name': 'Видеозвонок', 'verbose_name_plural': 'Видеозвонки'},
        ),
    ]
