# Generated by Django 4.2.20 on 2025-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="violations",
            field=models.ManyToManyField(to="account.violationtype"),
        ),
    ]
