# Generated by Django 4.2.20 on 2025-03-22 14:03

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_photo_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=account.models.get_avatar_path, verbose_name='Фото'),
        ),
    ]
