# Generated by Django 4.2.20 on 2025-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="Фото"),
        ),
    ]
