# Generated by Django 4.2.20 on 2025-03-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('S', 'Ученик'), ('T', 'Учитель')], max_length=2, verbose_name='Роль'),
        ),
    ]
