# Generated by Django 4.2.20 on 2025-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("W", "Женский")],
                default="M",
                max_length=1,
                verbose_name="Пол",
            ),
            preserve_default=False,
        ),
    ]
