# Generated by Django 4.2.20 on 2025-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("S", "Родитель"), ("P", "Учитель")],
                max_length=2,
                verbose_name="Роль",
            ),
        ),
    ]
