# Generated by Django 4.2.20 on 2025-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("S", "Родитель"), ("T", "Учитель")],
                max_length=2,
                verbose_name="Роль",
            ),
        ),
    ]
