# Generated by Django 4.2.20 on 2025-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="violations",
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("P", "Родитель"), ("T", "Учитель")],
                max_length=2,
                verbose_name="Роль",
            ),
        ),
        migrations.DeleteModel(
            name="ViolationType",
        ),
    ]
