# Generated by Django 4.2.20 on 2025-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_gender_role_alter_profile_gender_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='gender',
            name='code',
            field=models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Код пола'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код роли'),
        ),
    ]
