# Generated by Django 4.2.20 on 2025-04-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_remove_gender_id_remove_role_id_gender_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.gender",
                verbose_name="Пол",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.role",
                verbose_name="Роль",
            ),
            preserve_default=False,
        ),
    ]
