# Generated by Django 4.2.20 on 2025-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_remove_gender_code_remove_role_code_gender_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
