# Generated by Django 4.2.20 on 2025-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
