# Generated by Django 4.2.21 on 2026-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_search_distance',
            field=models.IntegerField(default=10, verbose_name='Максимальное расстояние поиска (км)'),
        ),
    ]
