# Generated by Django 4.2.21 on 2026-05-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_profile_location_address_profile_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
