# Generated by Django 4.2.21 on 2026-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_profile_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
