# Generated by Django 4.2.21 on 2026-05-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_profile_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_address',
        ),
    ]
