# Generated by Django 4.2.20 on 2025-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_detailed_info_alter_resume_short_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violationtype',
            options={'verbose_name': 'Вид нарушений', 'verbose_name_plural': 'Виды нарушений'},
        ),
    ]
