# Generated by Django 4.2.20 on 2025-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0006_alter_document_ver_status"),
        ("resume", "0004_alter_resume_document_delete_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="document",
        ),
        migrations.AddField(
            model_name="resume",
            name="documents",
            field=models.ManyToManyField(
                blank=True, to="document.document", verbose_name="Документы"
            ),
        ),
    ]
