# Generated by Django 4.2.21 on 2026-05-19 04:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0005_remove_resume_document_resume_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_level',
            field=models.PositiveIntegerField(default=0, help_text='0 - без образования, 10 - высшее профильное + учёная степень', verbose_name='Уровень образования (0-10)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='resume',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='resume',
            name='location_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='resume',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимальная цена (₽)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная цена (₽)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг (0-5)'),
        ),
        migrations.CreateModel(
            name='ExpertMatrixSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_data', models.JSONField(verbose_name='Данные матрицы')),
                ('weights_data', models.JSONField(verbose_name='Веса критериев')),
                ('consistency_ratio', models.FloatField(verbose_name='Отношение согласованности')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновлено экспертом')),
            ],
            options={
                'verbose_name': 'Настройка матрицы эксперта',
                'verbose_name_plural': 'Настройки матриц эксперта',
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(help_text='Ваш отзыв о работе преподавателя', max_length=1000, verbose_name='Комментарий')),
                ('is_approved', models.BooleanField(default=False, help_text='Отзыв проверен администратором', verbose_name='Проверен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Отзыв о преподавателе',
                'verbose_name_plural': 'Отзывы о преподавателях',
                'unique_together': {('teacher', 'parent')},
            },
        ),
    ]
