# Generated by Django 4.2.21 on 2026-05-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0006_resume_education_level_resume_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzyComparisonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_comparisons', models.TextField(blank=True, help_text='JSON с парными сравнениями критериев (шкала Саати)', null=True, verbose_name='Сравнения критериев')),
                ('alternative_comparisons', models.TextField(blank=True, help_text='JSON с парными сравнениями преподавателей по каждому критерию', null=True, verbose_name='Сравнения альтернатив')),
                ('criteria_weights', models.TextField(blank=True, help_text='JSON с рассчитанными весами критериев (α-коэффициенты)', null=True, verbose_name='Веса критериев')),
                ('use_expert_comparisons', models.BooleanField(default=False, help_text='Включить использование ручных экспертных парных сравнений', verbose_name='Использовать экспертные сравнения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Настройки нечеткого анализа (Беллман-Заде)',
                'verbose_name_plural': 'Настройки нечеткого анализа (Беллман-Заде)',
            },
        ),
    ]
