# Generated by Django 4.2.21 on 2026-05-21 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0007_fuzzycomparisonsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='teacherreview',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='UserCriteriaWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(help_text='JSON с весами критериев (α-коэффициенты)', verbose_name='Веса критериев')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_weights', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательские веса критериев',
                'verbose_name_plural': 'Пользовательские веса критериев',
                'unique_together': {('user',)},
            },
        ),
    ]
