# Generated by Django 4.2.21 on 2026-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_resume_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercriteriaweights',
            name='pairwise_comparisons',
            field=models.JSONField(blank=True, help_text='JSON с парными сравнениями критериев по шкале Саати', null=True, verbose_name='Парные сравнения'),
        ),
        migrations.AlterField(
            model_name='usercriteriaweights',
            name='weights',
            field=models.JSONField(blank=True, help_text='JSON с весами критериев (α-коэффициенты)', null=True, verbose_name='Веса критериев'),
        ),
    ]
