# Generated by Django 4.2.20 on 2025-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_remove_document_photo_document_user_documentimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="info",
            field=models.TextField(max_length=5000, verbose_name="Информация"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.TextField(max_length=400, verbose_name="Название"),
        ),
    ]
