# Generated by Django 4.2.20 on 2025-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_alter_document_info_alter_document_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=400, verbose_name="Название"),
        ),
    ]
