# Generated by Django 4.2.20 on 2025-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_ver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverificationstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название статуса'),
        ),
    ]
