# Generated by Django 4.2.20 on 2025-05-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpuzzle",
            options={
                "verbose_name": "Данные о пазле",
                "verbose_name_plural": "Данные о пазлах",
            },
        ),
    ]
