# Generated by Django 4.2.20 on 2025-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_userpuzzle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpuzzle',
            name='preset_image_path',
            field=models.CharField(blank=True, help_text='Путь к изображению из стандартного набора (если используется)', max_length=100, null=True, verbose_name='Путь к пресету изображения'),
        ),
    ]
