# Generated by Django 4.2.21 on 2025-07-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_userpuzzle_preset_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemoryGame',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memory_game_details', serialize=False, to='game.usergame')),
                ('name', models.CharField(help_text='Название, которое пользователь дает созданному экземпляру поиска пар', max_length=100, verbose_name="Название игры 'Поиск пар'")),
                ('pair_count', models.PositiveSmallIntegerField(help_text='Количество пар изображений, которые нужно найти для победы в игре', verbose_name='Количество пар')),
                ('card_layout', models.JSONField(help_text='JSON-массив индексов уникальных изображений (от 0 до pair_count-1)', verbose_name='Расположение карточек')),
                ('preset_name', models.CharField(blank=True, help_text='Название стандартного набора изображений (если используется)', max_length=50, null=True, verbose_name='Название пресета')),
                ('custom_image_paths', models.JSONField(blank=True, help_text='JSON-массив путей к файлам в медиа-хранилище', null=True, verbose_name='Пути к пользовательским изображениям')),
            ],
            options={
                'verbose_name': "Данные об игре 'Поиск пар'",
                'verbose_name_plural': "Данные об играх жанра 'Поиск пар'",
            },
        ),
    ]
