# Generated by Django 4.2.21 on 2026-08-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_usermemorygame'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSoundLoto',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sound_loto_details', serialize=False, to='game.usergame', verbose_name='Связь с базовой игрой')),
                ('name', models.CharField(help_text='Название, которое пользователь дает созданному экземпляру звукового лото', max_length=100, verbose_name="Название игры 'Звуковое лото'")),
                ('rounds_count', models.PositiveSmallIntegerField(default=4, help_text='Количество раундов в игре (от 2 до 6)', verbose_name='Количество раундов')),
                ('cards_count', models.PositiveSmallIntegerField(default=4, help_text='Количество карточек, показываемых одновременно (2, 3, 4 или 6)', verbose_name='Количество карточек на экране')),
                ('autoplay', models.BooleanField(default=True, help_text='Автоматически воспроизводить звук при показе карточек', verbose_name='Автовоспроизведение')),
                ('show_labels', models.BooleanField(default=True, help_text='Показывать текстовые подписи под карточками', verbose_name='Показывать подписи')),
                ('preset_name', models.CharField(blank=True, help_text='Название стандартного набора пар (если используется)', max_length=50, null=True, verbose_name='Название пресета')),
                ('custom_pairs', models.JSONField(blank=True, help_text='JSON-массив объектов с путями к изображениям, аудио и подписями', null=True, verbose_name='Пользовательские пары')),
            ],
            options={
                'verbose_name': "Данные об игре 'Звуковое лото'",
                'verbose_name_plural': "Данные об играх жанра 'Звуковое лото'",
            },
        ),
        migrations.AlterField(
            model_name='usergame',
            name='game_id',
            field=models.CharField(editable=False, help_text='Уникальный идентификатор игры формата ЖАНР-КОД (например, PZL-A1B2C3D4E5)', max_length=20, primary_key=True, serialize=False, verbose_name='Уникальный ID игры'),
        ),
        migrations.AlterField(
            model_name='usermemorygame',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memory_game_details', serialize=False, to='game.usergame', verbose_name='Связь с базовой игрой'),
        ),
        migrations.AlterField(
            model_name='userpuzzle',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='puzzle_details', serialize=False, to='game.usergame', verbose_name='Связь с базовой игрой'),
        ),
    ]
